network: TSEncoder
network_kwargs:
    input_size: 768
    max_frames: 64
    drop_rate: 0.1
    output_size:
    hidden_size: 768
    num_hidden_layers: 0
    vid_transform_kwargs:
        network: TemporalPoolTransformer
        network_kwargs:
            num_layers: 1
            num_heads: 4
            head_output_size: 64
            mlp_hidden_size: 256
            dropout: 0.1
    inst_transform_kwargs:
        network: TemporalPoolTransformer
        network_kwargs:
            num_layers: 1
            num_heads: 4
            head_output_size: 64
            mlp_hidden_size: 256
            dropout: 0.1
    ag_transform_kwargs:
        network: TemporalPoolTransformer
        network_kwargs:
            num_layers: 1
            num_heads: 4
            head_output_size: 64
            mlp_hidden_size: 256
            dropout: 0.1
    ai_transform_kwargs:
        network: TemporalPoolTransformer
        network_kwargs:
            num_layers: 1
            num_heads: 4
            head_output_size: 64
            mlp_hidden_size: 256
            dropout: 0.1
    gl_transform_kwargs:
        network: MLPTransform
        network_kwargs:
            num_layers: 2
            hidden_size: 512
    img_transform_kwargs:
        network: MLPTransform
        network_kwargs:
            num_layers: 2
            hidden_size: 512
